INSERT INTO USER (ID, USERNAME, PASSWORD, KINGDOM) VALUES (1, 'fooname', 'pass123', 'foodom');
INSERT INTO USER (ID, USERNAME, PASSWORD, KINGDOM) VALUES (2, 'dogname', 'pass456', 'dogdom');
INSERT INTO USER (ID, USERNAME, PASSWORD, KINGDOM) VALUES (3, 'admin', 'admin', 'admindom');